#define INST_ADDR_START     0x00000000
#define USRSYS_STACK_START  0x00010000  /* 64KB reserved for code/rodata */
#define SVC_STACK_START     0x00012000  /* 8KB */
#define IRQ_STACK_START     0x00014000  /* 8KB */
#define FIQ_STACK_START     0x00016000  /* 8KB */
#define ABT_STACK_START     0x00018000  /* 8KB */
#define UND_STACK_START     0x0001A000  /* 8KB */
#define TASK_STACK_START    0x0001C000  /* user tasks start here */
#define GLOBAL_ADDR_START   0x00028000  /* keep small gap for task stacks */
#define DALLOC_ADDR_START   0x0002C000  /* tiny heap region */

#define INST_MEM_SIZE       (USRSYS_STACK_START - INST_ADDR_START)
#define USRSYS_STACK_SIZE   (SVC_STACK_START - USRSYS_STACK_START)
#define SVC_STACK_SIZE      (IRQ_STACK_START - SVC_STACK_START)
#define IRQ_STACK_SIZE      (FIQ_STACK_START - IRQ_STACK_START)
#define FIQ_STACK_SIZE      (ABT_STACK_START - FIQ_STACK_START)
#define ABT_STACK_SIZE      (UND_STACK_START - ABT_STACK_START)
#define UND_STACK_SIZE      (TASK_STACK_START - UND_STACK_START)
#define TASK_STACK_SIZE     (GLOBAL_ADDR_START - TASK_STACK_START)

#define USR_TASK_STACK_SIZE 0x2000      /* 8KB per task */
#define DALLOC_MEM_SIZE     (0x4000)    /* 16KB heap */

#define USRSYS_STACK_TOP    (USRSYS_STACK_START + USRSYS_STACK_SIZE - 4)
#define SVC_STACK_TOP       (SVC_STACK_START + SVC_STACK_SIZE - 4)
#define IRQ_STACK_TOP       (IRQ_STACK_START + IRQ_STACK_SIZE - 4)
#define FIQ_STACK_TOP       (FIQ_STACK_START + FIQ_STACK_SIZE - 4)
#define ABT_STACK_TOP       (ABT_STACK_START + ABT_STACK_SIZE - 4)
#define UND_STACK_TOP       (UND_STACK_START + UND_STACK_SIZE - 4)
